version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=01it_group_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - manage_project
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - manage_project
    ports:
      - '8000:8000'
    volumes:
      - .:/code


networks:
  manage_project:

volumes:
  postgres-data: