version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=01it_group_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - manage_project
    ports:
      - '5432:5432'
 


networks:
  manage_project:

volumes:
  postgres-data:
