# Generated by Django 4.2.10 on 2024-02-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='01it.group/categories/'),
        ),
    ]
