# Generated by Django 4.2.10 on 2024-03-10 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Numbers without +7/8', regex='\\d{10}$')])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
