# Generated by Django 4.2.7 on 2023-11-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
