# Generated by Django 4.2.10 on 2024-02-18 07:00

from django.db import migrations, models


def update_order_products_price(apps, schema_editor):
    OrderProducts = apps.get_model('order', 'OrderedProducts')
    Product = apps.get_model('products', 'Product')

    product_prices = Product.objects.filter(id__in=OrderProducts.objects.values_list('product_id', flat=True)).values_list('id', 'price')
    prices_dict = {product_id: price for product_id, price in product_prices}


    to_update = []
    for order_product in OrderProducts.objects.all():
        product_price = prices_dict.get(order_product.product_id)
        if product_price is not None:
            order_product.price = product_price
            to_update.append(order_product)

    OrderProducts.objects.bulk_update(to_update, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_status_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='OrderedProducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(update_order_products_price, reverse_code=migrations.RunPython.noop)
    ]
