# Generated by Django 4.2.10 on 2024-03-05 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_for_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Numbers without +7/8', regex='\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
