# Generated by Django 4.2.10 on 2024-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_address_order_comment_for_address_order_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Abay 24C', max_length=255),
            preserve_default=False,
        ),
    ]
