# Generated by Django 4.2.11 on 2024-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('O', 'on_the_way')], default='P', max_length=1),
        ),
    ]
