# Generated by Django 4.2.11 on 2024-03-10 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinbasket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productsinbasket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
