# Generated by Django 4.2.8 on 2023-12-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.ImageField(null=True, upload_to='01it.group/products/'),
        ),
    ]
