# Generated by Django 4.2.10 on 2024-02-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='01it.group/products/'),
        ),
    ]
