# Generated by Django 4.2.11 on 2024-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_file',
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='01it.group/products/'),
        ),
    ]
